# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0002_auto_20171024_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='area',
        ),
        migrations.AlterField(
            model_name='studentcomplain',
            name='complaint_type',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('carpenter', 'carpenter'), ('plumber', 'plumber'), ('garbage', 'garbage'), ('dustbin', 'dustbin'), ('internet', 'internet'), ('other', 'other')], default='internet', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcomplain',
            name='worker_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='complaint_system.Workers'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='worker_type',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('carpenter', 'carpenter'), ('plumber', 'plumber'), ('garbage', 'garbage'), ('dustbin', 'dustbin'), ('internet', 'internet'), ('other', 'other')], default='internet', max_length=20),
        ),
    ]
