# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0004_auto_20171024_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomplain',
            name='feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='studentcomplain',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
