# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0005_auto_20171024_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='area',
            field=models.CharField(choices=[('hall-1', 'hall-1'), ('hall-3', 'hall-3'), ('hall-4', 'hall-4'), ('CC1', 'CC1'), ('CC2', 'CC2'), ('core_lab', 'core_lab'), ('LHTC', 'LHTC'), ('NR2', 'NR2'), ('Rewa_Residency', 'Rewa_Residency')], default='hall-3', max_length=20),
        ),
    ]
