# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0006_caretaker_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomplain',
            name='worker_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='complaint_system.Workers'),
        ),
    ]
