# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0008_auto_20171024_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='complaint_finish',
            field=models.DateTimeField(default=None),
        ),
    ]
