# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0010_auto_20171027_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomplain',
            name='complaint_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
