# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
