# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcomplain',
            name='com_id',
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='complaint_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='specific_location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
