# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171010_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_user_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_user_id', models.CharField(max_length=8)),
                ('c_location', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compl_id', models.IntegerField()),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='s_user_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_userid', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='supvisor_user_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_user_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='w_user_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_user_id', models.CharField(max_length=8)),
                ('w_location', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='flag',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='remarks',
            field=models.CharField(default='Pending', max_length=300),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='status',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='user_id',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
